/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as UsernameRouteImport } from './routes/username'
import { Route as TimestampRouteImport } from './routes/timestamp'
import { Route as SubdomainsRouteImport } from './routes/subdomains'
import { Route as SpeedtestRouteImport } from './routes/speedtest'
import { Route as ScamRouteImport } from './routes/scam'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as PortscanRouteImport } from './routes/portscan'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as NamintRouteImport } from './routes/namint'
import { Route as MosintRouteImport } from './routes/mosint'
import { Route as LeaklookerRouteImport } from './routes/leaklooker'
import { Route as IpRouteImport } from './routes/ip'
import { Route as HibpRouteImport } from './routes/hibp'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GitfiveRouteImport } from './routes/gitfive'
import { Route as GhuntRouteImport } from './routes/ghunt'
import { Route as GeocodeRouteImport } from './routes/geocode'
import { Route as FilephishRouteImport } from './routes/filephish'
import { Route as FaviconRouteImport } from './routes/favicon'
import { Route as ExifRouteImport } from './routes/exif'
import { Route as EncoderRouteImport } from './routes/encoder'
import { Route as EmailverifyRouteImport } from './routes/emailverify'
import { Route as EmailblacklistRouteImport } from './routes/emailblacklist'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ElaRouteImport } from './routes/ela'
import { Route as DorksRouteImport } from './routes/dorks'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as DatajudRouteImport } from './routes/datajud'
import { Route as CveRouteImport } from './routes/cve'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as CpfRouteImport } from './routes/cpf'
import { Route as CnpjRouteImport } from './routes/cnpj'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CepRouteImport } from './routes/cep'
import { Route as AbuseipdbRouteImport } from './routes/abuseipdb'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampRoute = TimestampRouteImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const SubdomainsRoute = SubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedtestRoute = SpeedtestRouteImport.update({
  id: '/speedtest',
  path: '/speedtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamRoute = ScamRouteImport.update({
  id: '/scam',
  path: '/scam',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const PortscanRoute = PortscanRouteImport.update({
  id: '/portscan',
  path: '/portscan',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const NamintRoute = NamintRouteImport.update({
  id: '/namint',
  path: '/namint',
  getParentRoute: () => rootRouteImport,
} as any)
const MosintRoute = MosintRouteImport.update({
  id: '/mosint',
  path: '/mosint',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaklookerRoute = LeaklookerRouteImport.update({
  id: '/leaklooker',
  path: '/leaklooker',
  getParentRoute: () => rootRouteImport,
} as any)
const IpRoute = IpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const HibpRoute = HibpRouteImport.update({
  id: '/hibp',
  path: '/hibp',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GitfiveRoute = GitfiveRouteImport.update({
  id: '/gitfive',
  path: '/gitfive',
  getParentRoute: () => rootRouteImport,
} as any)
const GhuntRoute = GhuntRouteImport.update({
  id: '/ghunt',
  path: '/ghunt',
  getParentRoute: () => rootRouteImport,
} as any)
const GeocodeRoute = GeocodeRouteImport.update({
  id: '/geocode',
  path: '/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const FilephishRoute = FilephishRouteImport.update({
  id: '/filephish',
  path: '/filephish',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconRoute = FaviconRouteImport.update({
  id: '/favicon',
  path: '/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ExifRoute = ExifRouteImport.update({
  id: '/exif',
  path: '/exif',
  getParentRoute: () => rootRouteImport,
} as any)
const EncoderRoute = EncoderRouteImport.update({
  id: '/encoder',
  path: '/encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailverifyRoute = EmailverifyRouteImport.update({
  id: '/emailverify',
  path: '/emailverify',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailblacklistRoute = EmailblacklistRouteImport.update({
  id: '/emailblacklist',
  path: '/emailblacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ElaRoute = ElaRouteImport.update({
  id: '/ela',
  path: '/ela',
  getParentRoute: () => rootRouteImport,
} as any)
const DorksRoute = DorksRouteImport.update({
  id: '/dorks',
  path: '/dorks',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DatajudRoute = DatajudRouteImport.update({
  id: '/datajud',
  path: '/datajud',
  getParentRoute: () => rootRouteImport,
} as any)
const CveRoute = CveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const CpfRoute = CpfRouteImport.update({
  id: '/cpf',
  path: '/cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const CnpjRoute = CnpjRouteImport.update({
  id: '/cnpj',
  path: '/cnpj',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CepRoute = CepRouteImport.update({
  id: '/cep',
  path: '/cep',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuseipdbRoute = AbuseipdbRouteImport.update({
  id: '/abuseipdb',
  path: '/abuseipdb',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/certificates': typeof CertificatesRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crypto': typeof CryptoRoute
  '/cve': typeof CveRoute
  '/datajud': typeof DatajudRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/ela': typeof ElaRoute
  '/email': typeof EmailRoute
  '/emailblacklist': typeof EmailblacklistRoute
  '/emailverify': typeof EmailverifyRoute
  '/encoder': typeof EncoderRoute
  '/exif': typeof ExifRoute
  '/favicon': typeof FaviconRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/graph': typeof GraphRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/hibp': typeof HibpRoute
  '/ip': typeof IpRoute
  '/leaklooker': typeof LeaklookerRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/password': typeof PasswordRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/regex': typeof RegexRoute
  '/registro': typeof RegistroRoute
  '/scam': typeof ScamRoute
  '/speedtest': typeof SpeedtestRoute
  '/subdomains': typeof SubdomainsRoute
  '/timestamp': typeof TimestampRoute
  '/username': typeof UsernameRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/certificates': typeof CertificatesRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crypto': typeof CryptoRoute
  '/cve': typeof CveRoute
  '/datajud': typeof DatajudRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/ela': typeof ElaRoute
  '/email': typeof EmailRoute
  '/emailblacklist': typeof EmailblacklistRoute
  '/emailverify': typeof EmailverifyRoute
  '/encoder': typeof EncoderRoute
  '/exif': typeof ExifRoute
  '/favicon': typeof FaviconRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/graph': typeof GraphRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/hibp': typeof HibpRoute
  '/ip': typeof IpRoute
  '/leaklooker': typeof LeaklookerRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/password': typeof PasswordRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/regex': typeof RegexRoute
  '/registro': typeof RegistroRoute
  '/scam': typeof ScamRoute
  '/speedtest': typeof SpeedtestRoute
  '/subdomains': typeof SubdomainsRoute
  '/timestamp': typeof TimestampRoute
  '/username': typeof UsernameRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/certificates': typeof CertificatesRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crypto': typeof CryptoRoute
  '/cve': typeof CveRoute
  '/datajud': typeof DatajudRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/ela': typeof ElaRoute
  '/email': typeof EmailRoute
  '/emailblacklist': typeof EmailblacklistRoute
  '/emailverify': typeof EmailverifyRoute
  '/encoder': typeof EncoderRoute
  '/exif': typeof ExifRoute
  '/favicon': typeof FaviconRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/graph': typeof GraphRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/hibp': typeof HibpRoute
  '/ip': typeof IpRoute
  '/leaklooker': typeof LeaklookerRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/password': typeof PasswordRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/regex': typeof RegexRoute
  '/registro': typeof RegistroRoute
  '/scam': typeof ScamRoute
  '/speedtest': typeof SpeedtestRoute
  '/subdomains': typeof SubdomainsRoute
  '/timestamp': typeof TimestampRoute
  '/username': typeof UsernameRoute
  '/whois': typeof WhoisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/certificates'
    | '/cnpj'
    | '/cpf'
    | '/crypto'
    | '/cve'
    | '/datajud'
    | '/dns'
    | '/dorks'
    | '/ela'
    | '/email'
    | '/emailblacklist'
    | '/emailverify'
    | '/encoder'
    | '/exif'
    | '/favicon'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/graph'
    | '/hash'
    | '/headers'
    | '/hibp'
    | '/ip'
    | '/leaklooker'
    | '/mosint'
    | '/namint'
    | '/password'
    | '/phone'
    | '/portscan'
    | '/regex'
    | '/registro'
    | '/scam'
    | '/speedtest'
    | '/subdomains'
    | '/timestamp'
    | '/username'
    | '/whois'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/certificates'
    | '/cnpj'
    | '/cpf'
    | '/crypto'
    | '/cve'
    | '/datajud'
    | '/dns'
    | '/dorks'
    | '/ela'
    | '/email'
    | '/emailblacklist'
    | '/emailverify'
    | '/encoder'
    | '/exif'
    | '/favicon'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/graph'
    | '/hash'
    | '/headers'
    | '/hibp'
    | '/ip'
    | '/leaklooker'
    | '/mosint'
    | '/namint'
    | '/password'
    | '/phone'
    | '/portscan'
    | '/regex'
    | '/registro'
    | '/scam'
    | '/speedtest'
    | '/subdomains'
    | '/timestamp'
    | '/username'
    | '/whois'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/certificates'
    | '/cnpj'
    | '/cpf'
    | '/crypto'
    | '/cve'
    | '/datajud'
    | '/dns'
    | '/dorks'
    | '/ela'
    | '/email'
    | '/emailblacklist'
    | '/emailverify'
    | '/encoder'
    | '/exif'
    | '/favicon'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/graph'
    | '/hash'
    | '/headers'
    | '/hibp'
    | '/ip'
    | '/leaklooker'
    | '/mosint'
    | '/namint'
    | '/password'
    | '/phone'
    | '/portscan'
    | '/regex'
    | '/registro'
    | '/scam'
    | '/speedtest'
    | '/subdomains'
    | '/timestamp'
    | '/username'
    | '/whois'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AbuseipdbRoute: typeof AbuseipdbRoute
  CepRoute: typeof CepRoute
  CertificatesRoute: typeof CertificatesRoute
  CnpjRoute: typeof CnpjRoute
  CpfRoute: typeof CpfRoute
  CryptoRoute: typeof CryptoRoute
  CveRoute: typeof CveRoute
  DatajudRoute: typeof DatajudRoute
  DnsRoute: typeof DnsRoute
  DorksRoute: typeof DorksRoute
  ElaRoute: typeof ElaRoute
  EmailRoute: typeof EmailRoute
  EmailblacklistRoute: typeof EmailblacklistRoute
  EmailverifyRoute: typeof EmailverifyRoute
  EncoderRoute: typeof EncoderRoute
  ExifRoute: typeof ExifRoute
  FaviconRoute: typeof FaviconRoute
  FilephishRoute: typeof FilephishRoute
  GeocodeRoute: typeof GeocodeRoute
  GhuntRoute: typeof GhuntRoute
  GitfiveRoute: typeof GitfiveRoute
  GraphRoute: typeof GraphRoute
  HashRoute: typeof HashRoute
  HeadersRoute: typeof HeadersRoute
  HibpRoute: typeof HibpRoute
  IpRoute: typeof IpRoute
  LeaklookerRoute: typeof LeaklookerRoute
  MosintRoute: typeof MosintRoute
  NamintRoute: typeof NamintRoute
  PasswordRoute: typeof PasswordRoute
  PhoneRoute: typeof PhoneRoute
  PortscanRoute: typeof PortscanRoute
  RegexRoute: typeof RegexRoute
  RegistroRoute: typeof RegistroRoute
  ScamRoute: typeof ScamRoute
  SpeedtestRoute: typeof SpeedtestRoute
  SubdomainsRoute: typeof SubdomainsRoute
  TimestampRoute: typeof TimestampRoute
  UsernameRoute: typeof UsernameRoute
  WhoisRoute: typeof WhoisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/username': {
      id: '/username'
      path: '/username'
      fullPath: '/username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamp': {
      id: '/timestamp'
      path: '/timestamp'
      fullPath: '/timestamp'
      preLoaderRoute: typeof TimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subdomains': {
      id: '/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof SubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speedtest': {
      id: '/speedtest'
      path: '/speedtest'
      fullPath: '/speedtest'
      preLoaderRoute: typeof SpeedtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam': {
      id: '/scam'
      path: '/scam'
      fullPath: '/scam'
      preLoaderRoute: typeof ScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portscan': {
      id: '/portscan'
      path: '/portscan'
      fullPath: '/portscan'
      preLoaderRoute: typeof PortscanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namint': {
      id: '/namint'
      path: '/namint'
      fullPath: '/namint'
      preLoaderRoute: typeof NamintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosint': {
      id: '/mosint'
      path: '/mosint'
      fullPath: '/mosint'
      preLoaderRoute: typeof MosintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaklooker': {
      id: '/leaklooker'
      path: '/leaklooker'
      fullPath: '/leaklooker'
      preLoaderRoute: typeof LeaklookerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip': {
      id: '/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof IpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hibp': {
      id: '/hibp'
      path: '/hibp'
      fullPath: '/hibp'
      preLoaderRoute: typeof HibpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitfive': {
      id: '/gitfive'
      path: '/gitfive'
      fullPath: '/gitfive'
      preLoaderRoute: typeof GitfiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghunt': {
      id: '/ghunt'
      path: '/ghunt'
      fullPath: '/ghunt'
      preLoaderRoute: typeof GhuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geocode': {
      id: '/geocode'
      path: '/geocode'
      fullPath: '/geocode'
      preLoaderRoute: typeof GeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filephish': {
      id: '/filephish'
      path: '/filephish'
      fullPath: '/filephish'
      preLoaderRoute: typeof FilephishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon': {
      id: '/favicon'
      path: '/favicon'
      fullPath: '/favicon'
      preLoaderRoute: typeof FaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exif': {
      id: '/exif'
      path: '/exif'
      fullPath: '/exif'
      preLoaderRoute: typeof ExifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encoder': {
      id: '/encoder'
      path: '/encoder'
      fullPath: '/encoder'
      preLoaderRoute: typeof EncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailverify': {
      id: '/emailverify'
      path: '/emailverify'
      fullPath: '/emailverify'
      preLoaderRoute: typeof EmailverifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailblacklist': {
      id: '/emailblacklist'
      path: '/emailblacklist'
      fullPath: '/emailblacklist'
      preLoaderRoute: typeof EmailblacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ela': {
      id: '/ela'
      path: '/ela'
      fullPath: '/ela'
      preLoaderRoute: typeof ElaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorks': {
      id: '/dorks'
      path: '/dorks'
      fullPath: '/dorks'
      preLoaderRoute: typeof DorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datajud': {
      id: '/datajud'
      path: '/datajud'
      fullPath: '/datajud'
      preLoaderRoute: typeof DatajudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cve': {
      id: '/cve'
      path: '/cve'
      fullPath: '/cve'
      preLoaderRoute: typeof CveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpf': {
      id: '/cpf'
      path: '/cpf'
      fullPath: '/cpf'
      preLoaderRoute: typeof CpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnpj': {
      id: '/cnpj'
      path: '/cnpj'
      fullPath: '/cnpj'
      preLoaderRoute: typeof CnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cep': {
      id: '/cep'
      path: '/cep'
      fullPath: '/cep'
      preLoaderRoute: typeof CepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abuseipdb': {
      id: '/abuseipdb'
      path: '/abuseipdb'
      fullPath: '/abuseipdb'
      preLoaderRoute: typeof AbuseipdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AbuseipdbRoute: AbuseipdbRoute,
  CepRoute: CepRoute,
  CertificatesRoute: CertificatesRoute,
  CnpjRoute: CnpjRoute,
  CpfRoute: CpfRoute,
  CryptoRoute: CryptoRoute,
  CveRoute: CveRoute,
  DatajudRoute: DatajudRoute,
  DnsRoute: DnsRoute,
  DorksRoute: DorksRoute,
  ElaRoute: ElaRoute,
  EmailRoute: EmailRoute,
  EmailblacklistRoute: EmailblacklistRoute,
  EmailverifyRoute: EmailverifyRoute,
  EncoderRoute: EncoderRoute,
  ExifRoute: ExifRoute,
  FaviconRoute: FaviconRoute,
  FilephishRoute: FilephishRoute,
  GeocodeRoute: GeocodeRoute,
  GhuntRoute: GhuntRoute,
  GitfiveRoute: GitfiveRoute,
  GraphRoute: GraphRoute,
  HashRoute: HashRoute,
  HeadersRoute: HeadersRoute,
  HibpRoute: HibpRoute,
  IpRoute: IpRoute,
  LeaklookerRoute: LeaklookerRoute,
  MosintRoute: MosintRoute,
  NamintRoute: NamintRoute,
  PasswordRoute: PasswordRoute,
  PhoneRoute: PhoneRoute,
  PortscanRoute: PortscanRoute,
  RegexRoute: RegexRoute,
  RegistroRoute: RegistroRoute,
  ScamRoute: ScamRoute,
  SpeedtestRoute: SpeedtestRoute,
  SubdomainsRoute: SubdomainsRoute,
  TimestampRoute: TimestampRoute,
  UsernameRoute: UsernameRoute,
  WhoisRoute: WhoisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
