/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as WaybackRouteImport } from './routes/wayback'
import { Route as UsernameRouteImport } from './routes/username'
import { Route as SubdomainsRouteImport } from './routes/subdomains'
import { Route as ScamRouteImport } from './routes/scam'
import { Route as PortscanRouteImport } from './routes/portscan'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as NamintRouteImport } from './routes/namint'
import { Route as MosintRouteImport } from './routes/mosint'
import { Route as IpRouteImport } from './routes/ip'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GitfiveRouteImport } from './routes/gitfive'
import { Route as GhuntRouteImport } from './routes/ghunt'
import { Route as GeocodeRouteImport } from './routes/geocode'
import { Route as FilephishRouteImport } from './routes/filephish'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DorksRouteImport } from './routes/dorks'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as CveRouteImport } from './routes/cve'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CpfRouteImport } from './routes/cpf'
import { Route as CnpjRouteImport } from './routes/cnpj'
import { Route as CepRouteImport } from './routes/cep'
import { Route as AbuseipdbRouteImport } from './routes/abuseipdb'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const WaybackRoute = WaybackRouteImport.update({
  id: '/wayback',
  path: '/wayback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => rootRouteImport,
} as any)
const SubdomainsRoute = SubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamRoute = ScamRouteImport.update({
  id: '/scam',
  path: '/scam',
  getParentRoute: () => rootRouteImport,
} as any)
const PortscanRoute = PortscanRouteImport.update({
  id: '/portscan',
  path: '/portscan',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const NamintRoute = NamintRouteImport.update({
  id: '/namint',
  path: '/namint',
  getParentRoute: () => rootRouteImport,
} as any)
const MosintRoute = MosintRouteImport.update({
  id: '/mosint',
  path: '/mosint',
  getParentRoute: () => rootRouteImport,
} as any)
const IpRoute = IpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GitfiveRoute = GitfiveRouteImport.update({
  id: '/gitfive',
  path: '/gitfive',
  getParentRoute: () => rootRouteImport,
} as any)
const GhuntRoute = GhuntRouteImport.update({
  id: '/ghunt',
  path: '/ghunt',
  getParentRoute: () => rootRouteImport,
} as any)
const GeocodeRoute = GeocodeRouteImport.update({
  id: '/geocode',
  path: '/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const FilephishRoute = FilephishRouteImport.update({
  id: '/filephish',
  path: '/filephish',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DorksRoute = DorksRouteImport.update({
  id: '/dorks',
  path: '/dorks',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const CveRoute = CveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CpfRoute = CpfRouteImport.update({
  id: '/cpf',
  path: '/cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const CnpjRoute = CnpjRouteImport.update({
  id: '/cnpj',
  path: '/cnpj',
  getParentRoute: () => rootRouteImport,
} as any)
const CepRoute = CepRouteImport.update({
  id: '/cep',
  path: '/cep',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuseipdbRoute = AbuseipdbRouteImport.update({
  id: '/abuseipdb',
  path: '/abuseipdb',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/scam': typeof ScamRoute
  '/subdomains': typeof SubdomainsRoute
  '/username': typeof UsernameRoute
  '/wayback': typeof WaybackRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/scam': typeof ScamRoute
  '/subdomains': typeof SubdomainsRoute
  '/username': typeof UsernameRoute
  '/wayback': typeof WaybackRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abuseipdb': typeof AbuseipdbRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/cpf': typeof CpfRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/filephish': typeof FilephishRoute
  '/geocode': typeof GeocodeRoute
  '/ghunt': typeof GhuntRoute
  '/gitfive': typeof GitfiveRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/mosint': typeof MosintRoute
  '/namint': typeof NamintRoute
  '/phone': typeof PhoneRoute
  '/portscan': typeof PortscanRoute
  '/scam': typeof ScamRoute
  '/subdomains': typeof SubdomainsRoute
  '/username': typeof UsernameRoute
  '/wayback': typeof WaybackRoute
  '/whois': typeof WhoisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/cnpj'
    | '/cpf'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/mosint'
    | '/namint'
    | '/phone'
    | '/portscan'
    | '/scam'
    | '/subdomains'
    | '/username'
    | '/wayback'
    | '/whois'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/cnpj'
    | '/cpf'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/mosint'
    | '/namint'
    | '/phone'
    | '/portscan'
    | '/scam'
    | '/subdomains'
    | '/username'
    | '/wayback'
    | '/whois'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/abuseipdb'
    | '/cep'
    | '/cnpj'
    | '/cpf'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/filephish'
    | '/geocode'
    | '/ghunt'
    | '/gitfive'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/mosint'
    | '/namint'
    | '/phone'
    | '/portscan'
    | '/scam'
    | '/subdomains'
    | '/username'
    | '/wayback'
    | '/whois'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AbuseipdbRoute: typeof AbuseipdbRoute
  CepRoute: typeof CepRoute
  CnpjRoute: typeof CnpjRoute
  CpfRoute: typeof CpfRoute
  CrmRoute: typeof CrmRoute
  CveRoute: typeof CveRoute
  DnsRoute: typeof DnsRoute
  DorksRoute: typeof DorksRoute
  EmailRoute: typeof EmailRoute
  FilephishRoute: typeof FilephishRoute
  GeocodeRoute: typeof GeocodeRoute
  GhuntRoute: typeof GhuntRoute
  GitfiveRoute: typeof GitfiveRoute
  HashRoute: typeof HashRoute
  HeadersRoute: typeof HeadersRoute
  IpRoute: typeof IpRoute
  MosintRoute: typeof MosintRoute
  NamintRoute: typeof NamintRoute
  PhoneRoute: typeof PhoneRoute
  PortscanRoute: typeof PortscanRoute
  ScamRoute: typeof ScamRoute
  SubdomainsRoute: typeof SubdomainsRoute
  UsernameRoute: typeof UsernameRoute
  WaybackRoute: typeof WaybackRoute
  WhoisRoute: typeof WhoisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wayback': {
      id: '/wayback'
      path: '/wayback'
      fullPath: '/wayback'
      preLoaderRoute: typeof WaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/username': {
      id: '/username'
      path: '/username'
      fullPath: '/username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subdomains': {
      id: '/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof SubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam': {
      id: '/scam'
      path: '/scam'
      fullPath: '/scam'
      preLoaderRoute: typeof ScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portscan': {
      id: '/portscan'
      path: '/portscan'
      fullPath: '/portscan'
      preLoaderRoute: typeof PortscanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namint': {
      id: '/namint'
      path: '/namint'
      fullPath: '/namint'
      preLoaderRoute: typeof NamintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosint': {
      id: '/mosint'
      path: '/mosint'
      fullPath: '/mosint'
      preLoaderRoute: typeof MosintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip': {
      id: '/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof IpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitfive': {
      id: '/gitfive'
      path: '/gitfive'
      fullPath: '/gitfive'
      preLoaderRoute: typeof GitfiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghunt': {
      id: '/ghunt'
      path: '/ghunt'
      fullPath: '/ghunt'
      preLoaderRoute: typeof GhuntRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geocode': {
      id: '/geocode'
      path: '/geocode'
      fullPath: '/geocode'
      preLoaderRoute: typeof GeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filephish': {
      id: '/filephish'
      path: '/filephish'
      fullPath: '/filephish'
      preLoaderRoute: typeof FilephishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorks': {
      id: '/dorks'
      path: '/dorks'
      fullPath: '/dorks'
      preLoaderRoute: typeof DorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cve': {
      id: '/cve'
      path: '/cve'
      fullPath: '/cve'
      preLoaderRoute: typeof CveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpf': {
      id: '/cpf'
      path: '/cpf'
      fullPath: '/cpf'
      preLoaderRoute: typeof CpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnpj': {
      id: '/cnpj'
      path: '/cnpj'
      fullPath: '/cnpj'
      preLoaderRoute: typeof CnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cep': {
      id: '/cep'
      path: '/cep'
      fullPath: '/cep'
      preLoaderRoute: typeof CepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abuseipdb': {
      id: '/abuseipdb'
      path: '/abuseipdb'
      fullPath: '/abuseipdb'
      preLoaderRoute: typeof AbuseipdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AbuseipdbRoute: AbuseipdbRoute,
  CepRoute: CepRoute,
  CnpjRoute: CnpjRoute,
  CpfRoute: CpfRoute,
  CrmRoute: CrmRoute,
  CveRoute: CveRoute,
  DnsRoute: DnsRoute,
  DorksRoute: DorksRoute,
  EmailRoute: EmailRoute,
  FilephishRoute: FilephishRoute,
  GeocodeRoute: GeocodeRoute,
  GhuntRoute: GhuntRoute,
  GitfiveRoute: GitfiveRoute,
  HashRoute: HashRoute,
  HeadersRoute: HeadersRoute,
  IpRoute: IpRoute,
  MosintRoute: MosintRoute,
  NamintRoute: NamintRoute,
  PhoneRoute: PhoneRoute,
  PortscanRoute: PortscanRoute,
  ScamRoute: ScamRoute,
  SubdomainsRoute: SubdomainsRoute,
  UsernameRoute: UsernameRoute,
  WaybackRoute: WaybackRoute,
  WhoisRoute: WhoisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
