/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisRouteImport } from './routes/whois'
import { Route as SubdomainsRouteImport } from './routes/subdomains'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScamRouteImport } from './routes/scam'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as IpRouteImport } from './routes/ip'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as HashRouteImport } from './routes/hash'
import { Route as GeocodeRouteImport } from './routes/geocode'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DorksRouteImport } from './routes/dorks'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as CveRouteImport } from './routes/cve'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CnpjRouteImport } from './routes/cnpj'
import { Route as CepRouteImport } from './routes/cep'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhoisRoute = WhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => rootRouteImport,
} as any)
const SubdomainsRoute = SubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamRoute = ScamRouteImport.update({
  id: '/scam',
  path: '/scam',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const IpRoute = IpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const GeocodeRoute = GeocodeRouteImport.update({
  id: '/geocode',
  path: '/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DorksRoute = DorksRouteImport.update({
  id: '/dorks',
  path: '/dorks',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const CveRoute = CveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CnpjRoute = CnpjRouteImport.update({
  id: '/cnpj',
  path: '/cnpj',
  getParentRoute: () => rootRouteImport,
} as any)
const CepRoute = CepRouteImport.update({
  id: '/cep',
  path: '/cep',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/geocode': typeof GeocodeRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/phone': typeof PhoneRoute
  '/scam': typeof ScamRoute
  '/search': typeof SearchRoute
  '/subdomains': typeof SubdomainsRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/geocode': typeof GeocodeRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/phone': typeof PhoneRoute
  '/scam': typeof ScamRoute
  '/search': typeof SearchRoute
  '/subdomains': typeof SubdomainsRoute
  '/whois': typeof WhoisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cep': typeof CepRoute
  '/cnpj': typeof CnpjRoute
  '/crm': typeof CrmRoute
  '/cve': typeof CveRoute
  '/dns': typeof DnsRoute
  '/dorks': typeof DorksRoute
  '/email': typeof EmailRoute
  '/geocode': typeof GeocodeRoute
  '/hash': typeof HashRoute
  '/headers': typeof HeadersRoute
  '/ip': typeof IpRoute
  '/phone': typeof PhoneRoute
  '/scam': typeof ScamRoute
  '/search': typeof SearchRoute
  '/subdomains': typeof SubdomainsRoute
  '/whois': typeof WhoisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cep'
    | '/cnpj'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/geocode'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/phone'
    | '/scam'
    | '/search'
    | '/subdomains'
    | '/whois'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cep'
    | '/cnpj'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/geocode'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/phone'
    | '/scam'
    | '/search'
    | '/subdomains'
    | '/whois'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cep'
    | '/cnpj'
    | '/crm'
    | '/cve'
    | '/dns'
    | '/dorks'
    | '/email'
    | '/geocode'
    | '/hash'
    | '/headers'
    | '/ip'
    | '/phone'
    | '/scam'
    | '/search'
    | '/subdomains'
    | '/whois'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CepRoute: typeof CepRoute
  CnpjRoute: typeof CnpjRoute
  CrmRoute: typeof CrmRoute
  CveRoute: typeof CveRoute
  DnsRoute: typeof DnsRoute
  DorksRoute: typeof DorksRoute
  EmailRoute: typeof EmailRoute
  GeocodeRoute: typeof GeocodeRoute
  HashRoute: typeof HashRoute
  HeadersRoute: typeof HeadersRoute
  IpRoute: typeof IpRoute
  PhoneRoute: typeof PhoneRoute
  ScamRoute: typeof ScamRoute
  SearchRoute: typeof SearchRoute
  SubdomainsRoute: typeof SubdomainsRoute
  WhoisRoute: typeof WhoisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whois': {
      id: '/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof WhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subdomains': {
      id: '/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof SubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam': {
      id: '/scam'
      path: '/scam'
      fullPath: '/scam'
      preLoaderRoute: typeof ScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip': {
      id: '/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof IpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geocode': {
      id: '/geocode'
      path: '/geocode'
      fullPath: '/geocode'
      preLoaderRoute: typeof GeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorks': {
      id: '/dorks'
      path: '/dorks'
      fullPath: '/dorks'
      preLoaderRoute: typeof DorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cve': {
      id: '/cve'
      path: '/cve'
      fullPath: '/cve'
      preLoaderRoute: typeof CveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnpj': {
      id: '/cnpj'
      path: '/cnpj'
      fullPath: '/cnpj'
      preLoaderRoute: typeof CnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cep': {
      id: '/cep'
      path: '/cep'
      fullPath: '/cep'
      preLoaderRoute: typeof CepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CepRoute: CepRoute,
  CnpjRoute: CnpjRoute,
  CrmRoute: CrmRoute,
  CveRoute: CveRoute,
  DnsRoute: DnsRoute,
  DorksRoute: DorksRoute,
  EmailRoute: EmailRoute,
  GeocodeRoute: GeocodeRoute,
  HashRoute: HashRoute,
  HeadersRoute: HeadersRoute,
  IpRoute: IpRoute,
  PhoneRoute: PhoneRoute,
  ScamRoute: ScamRoute,
  SearchRoute: SearchRoute,
  SubdomainsRoute: SubdomainsRoute,
  WhoisRoute: WhoisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
